### ISSUE TITLE
Performance tests

### ISSUE THREAD

**Issue by ayrat555** [omgnetwork/omg-childchain-v2#145]
Subtask of https://github.com/omgnetwork/childchain/issues/59 and https://github.com/omgnetwork/childchain/issues/141

# LoadTest.Runner.WatcherInfoAccountApi
##  Current behaviour

It creates and funds a single account on the childchain and then measures API responses multiple times for:
1. /account.get_balance
2. /account.get_utxos
3. /account.get_transactions
4. /transaction.create - the funded account sends the value back to the faucet account

No assertions are made during this test

## Suggested behaviour

Split this test into two separate tests:

1. Run multiple iterations of:

- create account
- send some amount to the created account on the childchain
- validate amount with `/account.get_balance`
- validate that the account has the required utxos with  `/account.get_utxos`

2. Run multiple iterations of

- create and fund account
- send some amount from created account to another account with `/transaction.create`
- validate created transaction with `/transaction.create`

# LoadTest.Runner.UtxosLoad
## Current behaviour

It has two scenarios:
1. Funds the account and creates multiple utxos
2. Sends utxos to another account

## Suggested behaviour

It can be separated into two tests:
1. The first test will create multiple utxos for different accounts validating it with /account.get_utxos
2. The second test will spend utxos validating balances.

As you can see in this case I'm suggesting only to add assertions.

# LoadTest.Runner.StandardExits
## Current behaviour

- Create many utxos
- Start exits for the created utxos

## Suggested behaviour

- Create many utxos validating that utxos are created
- Start exits validating balances on the rootchain

# LoadTest.Runner.Smoke
## Current behaviour

- checks status api endpoints for childchain, watcher_info and watcher

## Expected behaviour

I don't think it has to be ported (I don't think it's needed)

# LoadTest.Runner.ChildChainTransactions

## Current behaviour
- funds the account
- spends utxos

## Expected behaviour
It seems this test is already part of `LoadTest.Runner.UtxosLoad`.

For now, I won't delete existing tests, I will just create new ones that can be run from the command line using `mix run`. You can check an example of such test in https://github.com/omgnetwork/elixir-omg/pull/1745

**Comment by InoMurko** [comment]
Done, thanks @ayrat555
