### ISSUE TITLE
interpreting results of performance tests

### ISSUE THREAD

**Issue by ayrat555** [omgnetwork/omg-childchain-v2#149]
related issues/prs:

https://github.com/omgnetwork/childchain/issues/59
https://github.com/omgnetwork/childchain/issues/141
https://github.com/omgnetwork/childchain/issues/145
https://github.com/omgnetwork/elixir-omg/pull/1745

During code review discussions, the question about the interpretation of performance tests raised several times. 

Currently, by default successful outcome is defined by error_rate mean = 0. Optionally you can check error_rate percentile (10%-90%) = 0.

**Comment by InoMurko** [comment]
I think this is all done
