### ISSUE TITLE
vault immutability

### ISSUE THREAD

**Issue by InoMurko** [omgnetwork/omg-childchain-v2#58]
- How do we intend to use immutability-eth-plugin?

- Are there more use cases then calling `submitBlock(bytes32)` on plasma-framework contract?

- What is the purpose of contracts/?
https://github.com/omgnetwork/immutability-eth-plugin/tree/master/contracts
erc20 seems redundant. If plasma/ is used for testing, can we make them use our snapshots + geth + docker?

- It seems the only "plugin" we need is `path_plasma.go`. Can we remove others?
For example (they seem redundant - and, security wise, broadens the attack vector by having more APIs then we actually use):
```
ConfigPaths(&b),
WalletPaths(&b),
ERC20Paths(&b),
PlasmaPaths(&b),
AccountPaths(&b),
```

- Who calls `activateChildChain`? 
Plasma framework implementation:
https://github.com/omgnetwork/plasma-contracts/blob/705f8dedc62c0747abeb54b14f076c90b6cba99e/plasma_framework/docs/contracts/BlockController.md#activatechildchain
Is this somehow part of the immutability plugin? At the moment, this seems to be part of immutability plugin, but do we intend to use this? 
Implementation in the plugin:
https://github.com/omgnetwork/immutability-eth-plugin/blob/master/ethereum/path_plasma.go#L56
Currently, this is done by truffle: https://github.com/omgnetwork/plasma-contracts/blob/ee8230885012c0f21435c5ec02a4e37ab3ca81a3/plasma_framework/migrations/20_deploy_plasma_framework.js#L23

- `submitDepositBlock` is available in the immutability plugin. What is the use case for us? If there's none, can we remove it?
Implementation in the plugin:
https://github.com/omgnetwork/immutability-eth-plugin/blob/master/ethereum/path_plasma.go#L99

- API documentation is missing, I'm not sure we should rely just on scripts and tests.

**Comment by InoMurko** [comment]
Done

**Comment by kasima** [comment]
YES ✨ 🙌
