### ISSUE TITLE
Breakout Incoming Transactions into its own Unprocessed Transactions

### ISSUE THREAD

**Issue by achiurizo** [omgnetwork/omg-childchain-v2#68]
Following up a discussion with @InoMurko , we should consider breaking up our API/Transaction acceptance into two parts:

* Incoming transactions are validated by the protocol, and inserted into a separate table/database. API can return a "ACCEPTED"/202 response. Client needs to ask again to find out if it's been successful.
* Secondary process goes through that table, and does stateful checks. This will flip used outputs as spent or whatever and then fully insert this Transaction into the main Transaction table, awaiting to be submitted as a block

**Comment by InoMurko** [comment]
Not doing it.
